import {
  Worker,
  Job,
  Bid,
  Notification,
  EmployerProfile,
  Review,
} from '@/types';

export const mockEmployer: EmployerProfile = {
  id: 'emp-1',
  email: 'ahmed@company.pk',
  phone: '+92 300 1234567',
  name: 'Ahmed Khan',
  city: 'Lahore',
  company_name: 'Khan Builders',
  business_type: 'construction',
  role: 'employer',
  avatar_url: '',
  created_at: '2024-01-15T10:00:00Z',
  total_spent: 245500,
  jobs_posted: 18,
  avg_rating_given: 4.3,
  saved_workers_count: 7,
};

export const mockWorkers: Worker[] = [
  {
    id: 'w-1',
    name: 'Muhammad Ali',
    category: 'Plumber',
    city: 'Lahore',
    area: 'Gulberg',
    rating: 4.8,
    total_reviews: 47,
    experience_years: 8,
    hourly_rate: 500,
    daily_rate: 3500,
    avatar_url: '',
    phone: '+92 321 9876543',
    bio: 'Experienced plumber specializing in residential and commercial plumbing. Expert in pipe fitting, leak repair, and bathroom installations.',
    skills: ['Pipe Fitting', 'Leak Repair', 'Bathroom Installation', 'Water Heater'],
    is_available: true,
    completed_jobs: 156,
    created_at: '2023-06-10T08:00:00Z',
  },
  {
    id: 'w-2',
    name: 'Hassan Raza',
    category: 'Electrician',
    city: 'Lahore',
    area: 'DHA',
    rating: 4.6,
    total_reviews: 32,
    experience_years: 6,
    hourly_rate: 600,
    daily_rate: 4500,
    avatar_url: '',
    phone: '+92 312 4567890',
    bio: 'Licensed electrician with expertise in wiring, circuit installation, and electrical maintenance for homes and offices.',
    skills: ['Wiring', 'Circuit Installation', 'UPS Setup', 'Generator Repair'],
    is_available: true,
    completed_jobs: 98,
    created_at: '2023-08-15T09:00:00Z',
  },
  {
    id: 'w-3',
    name: 'Bilal Ahmed',
    category: 'Painter',
    city: 'Lahore',
    area: 'Model Town',
    rating: 4.9,
    total_reviews: 63,
    experience_years: 12,
    hourly_rate: 450,
    daily_rate: 3000,
    avatar_url: '',
    phone: '+92 333 5678901',
    bio: 'Master painter with over 12 years of experience. Specializing in interior, exterior, and decorative painting.',
    skills: ['Interior Painting', 'Exterior Painting', 'Wall Texturing', 'Wood Polish'],
    is_available: true,
    completed_jobs: 210,
    created_at: '2023-03-20T07:00:00Z',
  },
  {
    id: 'w-4',
    name: 'Imran Hussain',
    category: 'Carpenter',
    city: 'Karachi',
    area: 'Clifton',
    rating: 4.7,
    total_reviews: 41,
    experience_years: 10,
    hourly_rate: 550,
    daily_rate: 4000,
    avatar_url: '',
    phone: '+92 300 6789012',
    bio: 'Skilled carpenter with expertise in furniture making, door/window fitting, and woodwork restoration.',
    skills: ['Furniture Making', 'Door Fitting', 'Cabinet Work', 'Wood Restoration'],
    is_available: false,
    completed_jobs: 134,
    created_at: '2023-05-12T10:00:00Z',
  },
  {
    id: 'w-5',
    name: 'Tariq Mehmood',
    category: 'Mason',
    city: 'Islamabad',
    area: 'F-10',
    rating: 4.5,
    total_reviews: 28,
    experience_years: 15,
    hourly_rate: 500,
    daily_rate: 3500,
    avatar_url: '',
    phone: '+92 301 7890123',
    bio: 'Expert mason with 15 years of experience in construction. Specializing in brick work, plastering, and structural repairs.',
    skills: ['Brick Work', 'Plastering', 'Structural Repair', 'Tile Work'],
    is_available: true,
    completed_jobs: 178,
    created_at: '2023-02-28T06:00:00Z',
  },
  {
    id: 'w-6',
    name: 'Faisal Shah',
    category: 'AC Technician',
    city: 'Lahore',
    area: 'Johar Town',
    rating: 4.4,
    total_reviews: 19,
    experience_years: 5,
    hourly_rate: 700,
    daily_rate: 5000,
    avatar_url: '',
    phone: '+92 345 8901234',
    bio: 'Certified AC technician specializing in installation, repair, and maintenance of all brands of air conditioners.',
    skills: ['AC Installation', 'Gas Filling', 'Compressor Repair', 'Duct Cleaning'],
    is_available: true,
    completed_jobs: 87,
    created_at: '2023-09-05T11:00:00Z',
  },
  {
    id: 'w-7',
    name: 'Shoaib Malik',
    category: 'Welder',
    city: 'Karachi',
    area: 'Korangi',
    rating: 4.3,
    total_reviews: 22,
    experience_years: 9,
    hourly_rate: 600,
    daily_rate: 4000,
    avatar_url: '',
    phone: '+92 310 9012345',
    bio: 'Professional welder experienced in MIG, TIG, and arc welding. Worked on industrial and residential projects.',
    skills: ['MIG Welding', 'TIG Welding', 'Arc Welding', 'Metal Fabrication'],
    is_available: true,
    completed_jobs: 112,
    created_at: '2023-04-18T08:00:00Z',
  },
  {
    id: 'w-8',
    name: 'Rashid Khan',
    category: 'Driver',
    city: 'Lahore',
    area: 'Cantt',
    rating: 4.7,
    total_reviews: 35,
    experience_years: 11,
    hourly_rate: 400,
    daily_rate: 3000,
    avatar_url: '',
    phone: '+92 321 0123456',
    bio: 'Experienced driver with clean license. Comfortable with long routes, city driving, and corporate transportation.',
    skills: ['City Driving', 'Long Routes', 'Corporate Transport', 'Defensive Driving'],
    is_available: true,
    completed_jobs: 245,
    created_at: '2023-01-10T07:00:00Z',
  },
  {
    id: 'w-9',
    name: 'Nasir Iqbal',
    category: 'Cleaner',
    city: 'Islamabad',
    area: 'G-9',
    rating: 4.2,
    total_reviews: 15,
    experience_years: 3,
    hourly_rate: 300,
    daily_rate: 2000,
    avatar_url: '',
    phone: '+92 333 1234567',
    bio: 'Professional cleaning service provider for homes, offices, and commercial spaces. Thorough and reliable.',
    skills: ['Deep Cleaning', 'Office Cleaning', 'Window Cleaning', 'Post-Construction Cleanup'],
    is_available: true,
    completed_jobs: 67,
    created_at: '2023-11-20T09:00:00Z',
  },
  {
    id: 'w-10',
    name: 'Akhtar Muhammad',
    category: 'Laborer',
    city: 'Lahore',
    area: 'Shahdara',
    rating: 4.0,
    total_reviews: 12,
    experience_years: 7,
    hourly_rate: 350,
    daily_rate: 2500,
    avatar_url: '',
    phone: '+92 302 2345678',
    bio: 'Hardworking laborer experienced in construction, loading/unloading, and general helper duties.',
    skills: ['Construction Helper', 'Loading/Unloading', 'Digging', 'General Labor'],
    is_available: true,
    completed_jobs: 89,
    created_at: '2023-07-14T06:00:00Z',
  },
  {
    id: 'w-11',
    name: 'Zahid Hussain',
    category: 'Gardener',
    city: 'Islamabad',
    area: 'F-7',
    rating: 4.6,
    total_reviews: 21,
    experience_years: 8,
    hourly_rate: 400,
    daily_rate: 2800,
    avatar_url: '',
    phone: '+92 345 3456789',
    bio: 'Expert gardener specializing in landscape design, lawn maintenance, and plant care for residential and commercial properties.',
    skills: ['Landscape Design', 'Lawn Care', 'Plant Maintenance', 'Irrigation Systems'],
    is_available: true,
    completed_jobs: 95,
    created_at: '2023-06-01T07:00:00Z',
  },
  {
    id: 'w-12',
    name: 'Aslam Bhatti',
    category: 'Tailor',
    city: 'Karachi',
    area: 'Saddar',
    rating: 4.8,
    total_reviews: 55,
    experience_years: 14,
    hourly_rate: 350,
    daily_rate: 2500,
    avatar_url: '',
    phone: '+92 311 4567890',
    bio: 'Master tailor with expertise in both traditional and modern stitching. Specializing in suits, shalwar kameez, and alterations.',
    skills: ['Suit Stitching', 'Shalwar Kameez', 'Alterations', 'Embroidery'],
    is_available: true,
    completed_jobs: 312,
    created_at: '2023-02-10T08:00:00Z',
  },
  {
    id: 'w-13',
    name: 'Waqar Ahmed',
    category: 'Mechanic',
    city: 'Lahore',
    area: 'Badami Bagh',
    rating: 4.5,
    total_reviews: 38,
    experience_years: 10,
    hourly_rate: 500,
    daily_rate: 3500,
    avatar_url: '',
    phone: '+92 321 5678901',
    bio: 'Auto mechanic specializing in cars and motorcycles. Expert in engine repair, oil change, and full vehicle servicing.',
    skills: ['Engine Repair', 'Oil Change', 'Brake Service', 'AC Repair'],
    is_available: true,
    completed_jobs: 176,
    created_at: '2023-04-05T07:00:00Z',
  },
  {
    id: 'w-14',
    name: 'Kamran Siddiqui',
    category: 'Locksmith',
    city: 'Karachi',
    area: 'North Nazimabad',
    rating: 4.4,
    total_reviews: 17,
    experience_years: 6,
    hourly_rate: 800,
    daily_rate: 5000,
    avatar_url: '',
    phone: '+92 333 6789012',
    bio: 'Professional locksmith providing emergency lockout services, lock installation, key duplication, and security system setup.',
    skills: ['Emergency Lockout', 'Lock Installation', 'Key Duplication', 'Safe Opening'],
    is_available: true,
    completed_jobs: 73,
    created_at: '2023-10-08T10:00:00Z',
  },
];

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    employer_id: 'emp-1',
    employer_name: 'Ahmed Khan',
    category: 'Plumber',
    title: 'Bathroom Pipe Leakage Repair',
    description: 'Need an experienced plumber to fix pipe leakage in 2 bathrooms. The leaking pipes need to be replaced and proper sealing should be done.',
    budget_type: 'fixed',
    budget_amount: 8000,
    city: 'Lahore',
    area: 'Gulberg',
    address: '23-B, Gulberg III, Lahore',
    date: '2025-01-20',
    time: '09:00 AM',
    urgency: 'urgent',
    workers_needed: 1,
    duration: '4-5 hours',
    skills_required: ['Pipe Fitting', 'Leak Repair'],
    status: 'open',
    created_at: '2025-01-18T10:30:00Z',
    bids_count: 3,
  },
  {
    id: 'job-2',
    employer_id: 'emp-1',
    employer_name: 'Ahmed Khan',
    category: 'Painter',
    title: 'Full House Interior Painting',
    description: 'Need painters for complete interior painting of a 5-marla house. 4 rooms, 2 bathrooms, kitchen, and living room. Includes wall preparation and 2 coats of paint.',
    budget_type: 'fixed',
    budget_amount: 65000,
    city: 'Lahore',
    area: 'Model Town',
    address: '15-A, Block C, Model Town, Lahore',
    date: '2025-02-01',
    time: '08:00 AM',
    urgency: 'normal',
    workers_needed: 2,
    duration: '5-6 days',
    skills_required: ['Interior Painting', 'Wall Preparation'],
    status: 'open',
    created_at: '2025-01-19T14:00:00Z',
    bids_count: 5,
  },
  {
    id: 'job-3',
    employer_id: 'emp-1',
    employer_name: 'Ahmed Khan',
    category: 'Electrician',
    title: 'Office Wiring and UPS Installation',
    description: 'Need an electrician for new office setup. Wiring for 10 rooms, UPS installation (3kVA), and installation of ceiling fans and lights.',
    budget_type: 'fixed',
    budget_amount: 45000,
    city: 'Lahore',
    area: 'DHA',
    address: 'Office #7, 2nd Floor, DHA Phase 5, Lahore',
    date: '2025-01-25',
    time: '10:00 AM',
    urgency: 'urgent',
    workers_needed: 1,
    duration: '2-3 days',
    skills_required: ['Wiring', 'UPS Setup'],
    status: 'in_progress',
    accepted_bid_id: 'bid-1',
    created_at: '2025-01-15T09:00:00Z',
    bids_count: 4,
  },
  {
    id: 'job-4',
    employer_id: 'emp-1',
    employer_name: 'Ahmed Khan',
    category: 'Mason',
    title: 'Boundary Wall Construction',
    description: 'Need experienced masons for constructing a boundary wall (40 feet length, 8 feet height). Includes foundation work and plastering.',
    budget_type: 'daily',
    budget_amount: 2500,
    city: 'Islamabad',
    area: 'F-10',
    address: 'Plot #12, Street 5, F-10/3, Islamabad',
    date: '2025-01-10',
    urgency: 'normal',
    workers_needed: 3,
    duration: '7-8 days',
    skills_required: ['Brick Work', 'Plastering'],
    status: 'completed',
    accepted_bid_id: 'bid-2',
    created_at: '2025-01-05T08:00:00Z',
    bids_count: 6,
  },
  {
    id: 'job-5',
    employer_id: 'emp-1',
    employer_name: 'Ahmed Khan',
    category: 'Driver',
    title: 'Monthly Corporate Driver Needed',
    description: 'Looking for a reliable driver for daily office pickup/drop. Suzuki Cultus or similar. Route: Model Town to Gulberg. Timings: 8 AM - 6 PM.',
    budget_type: 'fixed',
    budget_amount: 30000,
    city: 'Lahore',
    area: 'Model Town',
    date: '2025-02-01',
    urgency: 'normal',
    workers_needed: 1,
    duration: '1 month',
    skills_required: ['City Driving', 'Corporate Transport'],
    status: 'cancelled',
    created_at: '2025-01-12T11:00:00Z',
    bids_count: 8,
  },
  {
    id: 'job-6',
    employer_id: 'emp-1',
    employer_name: 'Ahmed Khan',
    category: 'Cleaner',
    title: 'Post-Construction Cleanup',
    description: 'Need cleaners for post-construction cleanup of a newly built house. Includes debris removal, floor cleaning, window cleaning, and general tidying.',
    budget_type: 'fixed',
    budget_amount: 12000,
    city: 'Lahore',
    area: 'DHA',
    date: '2025-01-22',
    time: '07:00 AM',
    urgency: 'normal',
    workers_needed: 3,
    duration: '1 day',
    skills_required: ['Deep Cleaning', 'Post-Construction Cleanup'],
    status: 'open',
    created_at: '2025-01-20T16:00:00Z',
    bids_count: 2,
  },
];

export const mockBids: Bid[] = [
  {
    id: 'bid-1',
    job_id: 'job-3',
    worker_id: 'w-2',
    worker: mockWorkers[1],
    amount: 42000,
    message: 'I can complete the wiring and UPS installation in 2 days. I have experience with office setups and will bring all necessary tools.',
    estimated_duration: '2 days',
    status: 'accepted',
    created_at: '2025-01-15T12:00:00Z',
  },
  {
    id: 'bid-2',
    job_id: 'job-4',
    worker_id: 'w-5',
    worker: mockWorkers[4],
    amount: 70000,
    message: 'I can bring my team of 3 experienced masons. We have done similar boundary wall projects before.',
    estimated_duration: '7 days',
    status: 'accepted',
    created_at: '2025-01-05T10:00:00Z',
  },
  {
    id: 'bid-3',
    job_id: 'job-1',
    worker_id: 'w-1',
    worker: mockWorkers[0],
    amount: 7500,
    message: 'I can fix both bathroom leaks within 4 hours. I carry all pipe fittings and sealants with me.',
    estimated_duration: '4 hours',
    status: 'pending',
    created_at: '2025-01-18T11:00:00Z',
  },
  {
    id: 'bid-4',
    job_id: 'job-1',
    worker_id: 'w-10',
    worker: mockWorkers[9],
    amount: 6500,
    message: 'I can do this work at a reasonable price. Will bring the necessary materials and tools.',
    estimated_duration: '5 hours',
    status: 'pending',
    created_at: '2025-01-18T12:30:00Z',
  },
  {
    id: 'bid-5',
    job_id: 'job-2',
    worker_id: 'w-3',
    worker: mockWorkers[2],
    amount: 60000,
    message: 'My team of 2 can complete the full interior painting in 5 days. We use premium quality paints and ensure proper wall preparation.',
    estimated_duration: '5 days',
    status: 'pending',
    created_at: '2025-01-19T15:00:00Z',
  },
  {
    id: 'bid-6',
    job_id: 'job-2',
    worker_id: 'w-9',
    worker: mockWorkers[8],
    amount: 55000,
    message: 'We are a team of experienced painters. Will provide quality work with guarantee.',
    estimated_duration: '6 days',
    status: 'pending',
    created_at: '2025-01-19T16:00:00Z',
  },
  {
    id: 'bid-7',
    job_id: 'job-6',
    worker_id: 'w-9',
    worker: mockWorkers[8],
    amount: 10000,
    message: 'I can bring 2 more cleaners with me. We will complete the cleanup in one day.',
    estimated_duration: '1 day',
    status: 'pending',
    created_at: '2025-01-20T17:00:00Z',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'n-1',
    user_id: 'emp-1',
    type: 'new_bid',
    title: 'New Bid Received',
    message: 'Muhammad Ali bid PKR 7,500 on "Bathroom Pipe Leakage Repair"',
    read: false,
    related_id: 'bid-3',
    created_at: '2025-01-18T11:00:00Z',
  },
  {
    id: 'n-2',
    user_id: 'emp-1',
    type: 'new_bid',
    title: 'New Bid Received',
    message: 'Bilal Ahmed bid PKR 60,000 on "Full House Interior Painting"',
    read: false,
    related_id: 'bid-5',
    created_at: '2025-01-19T15:00:00Z',
  },
  {
    id: 'n-3',
    user_id: 'emp-1',
    type: 'bid_accepted',
    title: 'Bid Accepted',
    message: 'You accepted Hassan Raza\'s bid for "Office Wiring and UPS Installation"',
    read: true,
    related_id: 'job-3',
    created_at: '2025-01-16T09:00:00Z',
  },
  {
    id: 'n-4',
    user_id: 'emp-1',
    type: 'job_completed',
    title: 'Job Completed',
    message: 'Tariq Mehmood has completed "Boundary Wall Construction"',
    read: true,
    related_id: 'job-4',
    created_at: '2025-01-13T17:00:00Z',
  },
  {
    id: 'n-5',
    user_id: 'emp-1',
    type: 'system',
    title: 'Welcome to MazdoorPing!',
    message: 'Get started by posting your first job or browsing workers.',
    read: true,
    created_at: '2025-01-15T10:00:00Z',
  },
  {
    id: 'n-6',
    user_id: 'emp-1',
    type: 'new_review',
    title: 'New Review',
    message: 'You received a 5-star review from Tariq Mehmood',
    read: true,
    related_id: 'job-4',
    created_at: '2025-01-14T10:00:00Z',
  },
];

export const mockReviews: Review[] = [
  {
    id: 'r-1',
    job_id: 'job-4',
    worker_id: 'w-5',
    employer_id: 'emp-1',
    employer_name: 'Ahmed Khan',
    rating: 5,
    comment: 'Excellent work! Tariq and his team built the boundary wall perfectly. Very professional and punctual.',
    is_anonymous: false,
    created_at: '2025-01-14T10:00:00Z',
  },
  {
    id: 'r-2',
    job_id: 'job-3',
    worker_id: 'w-2',
    employer_id: 'emp-1',
    employer_name: 'Ahmed Khan',
    rating: 4,
    comment: 'Good work overall. Wiring was neat and UPS works perfectly. Could have been a bit faster.',
    is_anonymous: false,
    created_at: '2025-01-17T14:00:00Z',
  },
];

export const mockSavedWorkerIds = ['w-1', 'w-3', 'w-5', 'w-8', 'w-12'];

export function getJobsWithBids(jobs: Job[], bids: Bid[]): (Job & { bids: Bid[] })[] {
  return jobs.map((job) => ({
    ...job,
    bids: bids.filter((b) => b.job_id === job.id),
  }));
}

export function getWorkerReviews(workerId: string, reviews: Review[]): Review[] {
  return reviews.filter((r) => r.worker_id === workerId);
}
